### ISSUE TITLE
Question about what is the role of the mapper

### ISSUE THREAD

**Issue by zhaojunGUO** [Georgefwt/AquaLoRA#10]
Hello, i know that the role of mapper is to achieve watermark's flexibility, allowing arbitrary changes to the embedded secret during utilization. But if i only want to embedding a fixed watermark, can i delete the training of mapper? I tried to delete the mapper, but the trained lora only generate a noise.
![0](https://github.com/user-attachments/assets/5564083e-4562-481d-8653-9192440227e0)

**Comment by Hlufies** [comment]
SAME ISSUE!

**Comment by Georgefwt** [comment]
I'm not quite sure about your implementation method. Could you provide more details?

**Comment by zhaojunGUO** [comment]
hello, I solved this, issue think i made some mistakes when reproduce your code, i close this issue, thank you very much
