### ISSUE TITLE
Problem about metric TPR (FPR=10^-6)

### ISSUE THREAD

**Issue by asdcaszc** [Georgefwt/AquaLoRA#2]
Hi,

This work is very good but I still have some problems.

How to calculate the TPR (FPR=10^-6) for other methods like Stable Signature? How to set the threshold in Stable Signature which you did not mention in your paper? Does it mean you extract the watermark from the original images without watermarks and calculate the FPR and TPR?

Waiting for your reply. Thank you very much.

**Comment by Georgefwt** [comment]
Thank you for your interest in our paper! Apologies for not having had the time to respond to your questions earlier. In our work, we consider the watermark extracted from clean images to follow a Bernoulli distribution. This assumption is also utilized in previous studies [[1]](https://arxiv.org/abs/2303.15435). Based on this, we can estimate the threshold. The detailed calculation process is provided in Appendix F of [our paper](https://arxiv.org/abs/2405.11135v1).

[1] P. Fernandez, G. Couairon, H. Jégou, M. Douze, and T. Furon, “The Stable Signature: Rooting Watermarks in Latent Diffusion Models,”

**Comment by asdcaszc** [comment]
Thanks for your kind reply. I have checked TPR in your paper but I have a problem. Is it sensitive for low-bit watermarking? For example, if the watermark bit numebr is 8 so that their threshold have to be 8 in the situation FPR=10^-6 (1-B(0.5;1,8)=1-0.996=0.004).

**Comment by Georgefwt** [comment]
Yes, this metric is sensitive to the number of watermark bits. Large-capacity watermarks have a relative advantage in this metric. For low-bit watermarks, like the 8-bit example you mentioned, it is essentially necessary to extract all bits correctly.

**Comment by Georgefwt** [comment]
I'm now going to close this issue. If you have more questions, feel free to ask!
