### ISSUE TITLE
ValueError when set the correct LoRA layers

### ISSUE THREAD

**Issue by quang-ngh** [Georgefwt/AquaLoRA#3]
Hi, when i run the train script `ppft_train.py` with `runwayml/stable-diffusion-v1-5` and it raise a error like this. Can you double check the code? 

![image](https://github.com/user-attachments/assets/5ae03cdf-0265-44c8-bb92-2ec4171ad89a)

**Comment by Georgefwt** [comment]
Can you make sure you install the correct version of diffusers? You can post your environment here.
