### ISSUE TITLE
`msgdecoder` in `ppft_train.py`

### ISSUE THREAD

**Issue by Xiao-Fangff** [Georgefwt/AquaLoRA#4]
Hi, I have discovered that the parameters of the `msgdecoder` in the `ppft_train.py` are frozen.

![22f03ed361098d24f2d115478afb7f1](https://github.com/user-attachments/assets/3b60cef7-5cc1-4b2c-9bb3-6bdc87e1fc0b)

But why is the `msgdecoder` being optimized in the optimizer?

![39656d519844b30e8500335b2c4e31b](https://github.com/user-attachments/assets/a60ddeed-3fb6-4e50-9c76-f0ab05b93b7c)

**Comment by Georgefwt** [comment]
Indeed. `msgdecoder` should not be included in optimizer params though it won't break the whole training pipeline. I will fix it ASAP.

**Comment by Xiao-Fangff** [comment]
Thanks for your prompt reply!
