### ISSUE TITLE
How do I get fid_outputs/coco/metadata.json or fid_outputs/coco/ground_truth?

### ISSUE THREAD

**Issue by mochiduki-01** [Georgefwt/AquaLoRA#7]
Hello.
I am trying to run evaluation/run_fid.py to calcurate the FID, but I get an error that 'fid_outputs/coco/meta_data.json' is not found.
“FileNotFoundError: [Errno 2] No such file or directory: 'fid_outputs/coco/meta_data.json'”.

**Comment by Georgefwt** [comment]
We follow the fid calculation process in the Tree-ring watermark. You can find the metadata file here:
https://github.com/YuxinWenRick/tree-ring-watermark?tab=readme-ov-file#calculate-fid

I also upload another one here [meta_data.json](https://github.com/user-attachments/files/17600553/meta_data.json) for sharing.

**Comment by mochiduki-01** [comment]
I was able to find both metadata.json and ground_truch.
Many thanks.
