### ISSUE TITLE
Question about training the text encoder

### ISSUE THREAD

**Issue by zhaojunGUO** [Georgefwt/AquaLoRA#9]
Hi, I don't seem to see in the paper that you guys trained the text encoder as well, and I'm wondering why you need to train the text encoder (why you adding lora to the text encoder as well)

**Comment by Georgefwt** [comment]
Hi, we haven't trained the text encoder. The code related to the text encoder comes from the diffuser scripts that haven't been deleted.

**Comment by zhaojunGUO** [comment]
thank you for your reply~
